name: map_zone_manager
description: "A Flutter package to manage zones on a Google Map."
version: 0.0.1
homepage: https://github.com/muhsindev4/map_zone_manager
repository: https://github.com/muhsindev4/map_zone_manager

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


